# Versions used to build for Minecraft 26.3
# fabric_version: https://modmuss50.me/fabric.html
# the others: https://modrinth.com/mod/vivecraft/versions, .../cloth-config/versions, .../modmenu/versions
minecraft_version=26.3
fabric_version=0.161.0+26.3
vivecraft_version=26.3-1.3.16-fabric
cloth_config_version=26.3.159+fabric
modmenu_version=21.0.0
# NoFigura 0.1.6.7+26.3, https://modrinth.com/mod/nofigura/versions
figura_version=XGi4PCzg
